AARs/urls.py
''' Defines URL patterns for AARs app '''

from django.urls import path

from . import views

app_name = 'AARs'

urlpatterns = [
    # Home Page
    path('', views.index, name ='index'),

    # Show all topics
    path('topics/', views.topics, name='topics'),

    # Detail page for a single topics
    path('topics/<int:topic_id>/', views.topic, name='topic'),

    # Page for adding a new topic
    path('new_topic/', views.new_topic, name='new_topic'),

    # Page for adding new actions to review
    path('new_action/<int:topic_id>/', views.new_action, name = 'new_action'),

    # Page for editing an entry
    path('edit_action/<int:action_id>/', views.edit_action,
        name='edit_action'),

]

daily_AAR/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('AARs.urls')),
]

users/urls.py
""" Defines URL patterns for users """

from django.urls import path
from django.contrib.auth.views import LoginView

from . import views

app_name = 'users'
urlpatterns = [
    # Login page
    path('login/', LoginView.as_view(template_name = 'users/login.html'), name='login'),

    # Logout Page
    path('logout/', views.logout_view, name='logout'),

    # Registration page
    path('register/', views.register, name='register'),
]

AARs/models.py
from django.db import models
from django.contrib.auth.models import User

class Topic(models.Model):
    ''' A topic categorizing actions or outcomes '''
    text = models.CharField(max_length=50)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)


    def __str__(self):
        ''' returns a string representation of the model '''
        return self.text

class Actions(models.Model):
    ''' a specific action or outcome to be reviewed '''
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        ''' returns string representation of model '''
        return self.text[0:50] + "..."

users/models.py
from django.db import models

# Create your models here.

AARs/forms.py
from django import forms

from .models import Topic, Actions

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class ActionForm(forms.ModelForm):
    class Meta:
        model = Actions
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols':80})}

AARs/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .models import Topic, Actions
from .forms import TopicForm, ActionForm

def index(request):
    ''' The home page for After Action Reports (AARs) '''
    return render(request, 'AARs/index.html')

@login_required
def topics(request):
    ''' shows all topics '''
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'AARs/topics.html', context)

@login_required
def topic(request, topic_id):
    '''Show a single topic and all its entries '''
    topic = get_object_or_404(Topic, id=topic_id)
    # Make sure the topic belongs to the current user
    if topic.owner != request.user:
        raise Http404
    actions = topic.actions_set.order_by('-date_added')
    context = {'topic': topic, 'actions': actions}
    return render(request, 'AARs/topic.html', context)

@login_required
def new_topic(request):
    """ Add a new topic """
    if request.method != 'POST':
        # No data submitted; create a blank form
        form = TopicForm
    else:
        # POST data submitted; process data
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('AARs:topics'))
    context = {'form': form}
    return render(request, 'AARs/new_topic.html', context)

@login_required
def new_action(request, topic_id):
    """ Add a new action to review """
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        # No data submitted; create a blank form
        form = ActionForm()
    else:
        # POST data submitted; process data
        form = ActionForm(data=request.POST)
        if form.is_valid():
            new_action = form.save(commit=False)
            new_action.topic = topic
            new_action.save()
            return HttpResponseRedirect(reverse('AARs:topic', args=[topic_id]))

    context = {'topic': topic, 'form': form}
    return render(request, 'AARs/new_action.html', context)

@login_required
def edit_action(request, action_id):
    ''' Edit an existing action entry '''
    action = Actions.objects.get(id=action_id)
    topic = action.topic
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        # Initial request. Pre-fill form with current action
        form = ActionForm(instance=action)
    else:
        # POST data submitted, process data
        form = ActionForm(instance=action, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('AARs:topic', args=[topic.id]))
    context = {'action':action, 'topic':topic, 'form': form}
    return render(request, 'AARs/edit_action.html', context)

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm


def logout_view(request):
    ''' log the user out '''

    logout(request)
    return HttpResponseRedirect(reverse('AARs:index'))

def register(request):
    ''' register a new user '''
    if request.method != 'POST':
        # Display blank registration form
        form = UserCreationForm()
    else:
        # Process completed form
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Log the user in and redirect to home page
            authenticated_user = authenticate(username = new_user.username,
                password = request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('AARs:index'))

    context = {'form': form}
    return render(request, 'users/register.html', context)

AARs/templates/AARs/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name = "viewport" content="width=device-width, initial-scale=1">

    <title>After Action Report</title>

    {% bootstrap_css %}
    {% bootstrap_javascript %}

  </head>

  <body>
    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">

        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed"
            data-toggle="collapse" data-target="#navbar"
            aria-expanded="false" aria-controls="navbar">
          </button>
          <a class="navbar-brand" href="{% url 'AARs:index' %}">
            After Action Reports</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'AARs:topics' %}">Topics</a></li>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
              <li><a>Hello, {{ user.username }}.<a></li>
              <li><a href="{% url 'users:logout' %}">Log out</a></li>
            {% else %}
              <li><a href="{% url 'users:register' %}">Register</a></li>
              <li><a href="{% url 'users:login' %}">Log In</a></li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->

      </div>
    </nav>

    <div class="container">

      <div class="page-header">
        {% block header %}{% endblock header %}
      </div>
      <div>
        {% block content %}{% endblock content %}
      </div>

    </div> <!-- /container -->

  </body>
</html>

AARs/templates/AARs/edit_action.html
{% extends "AARs/base.html" %}

{% block content %}

  <p><a href="{% url 'AARs:topic' topic.id %}">{{ topic }}</a></p>

  <p>Edit</p>

  <form action="{% url 'AARs:edit_action' action.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Save Changes</button>
  </form>

{% endblock content %}

AARs/templates/AARs/index.html
{% extends "AARs/base.html" %}

{% block header %}
  <div class="jumbotron">
    <h1>Reflect. Design. Implement. Improve. Repeat</h1>
  </div>
{% endblock header %}

{% block content %}
  <h2>
    <a href="{% url 'users:register' %}">Register an account</a> to make your own AAR
    and list the daily actions, habits, and routines you want to improve.
  </h2>
  <h2>
    The After Action Reports help you review your actions and outcomes and to
    investigate them for ways to improve; to ensure the good things are continued and
    the bad things are minimized and eliminated.
  </h2>
  <h2>
    It is a way to build, one small system at a time, an ever improving system for your life.
  </h2>

{% endblock content %}

AARs/templates/AARs/new_action.html
{% extends "AARs/base.html" %}

{% block content %}

  <p><a href="{% url 'AARs:topic' topic.id %}">{{ topic }}</a></p>

  <p>Add a new action to reveiw: </p>

  <form action="{% url 'AARs:new_action' topic.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Add Action to Review</button>
  </form>
{% endblock content %}

AARs/templates/AARs/new_topic.html
{% extends "AARs/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>Add a new Topic</h2>
{% endblock header %}

{% block content %}
  <form class="form" action="{% url 'AARs:new_topic' %}" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
      <button name="submit" class="btn btn-primary">Add Topic</button>
    {% endbuttons %}
  </form>
{% endblock content %}

AARs/templates/AARs/topic.html
{% extends "AARs/base.html" %}

{% block header %}
  <h2>{{ topic }}</h2>
{% endblock header %}

{% block content %}
  <p>
    <a href="{% url 'AARs:new_action' topic.id %}">Add new action</a>
  </p>

  {% for action in actions %}
    <div class="panel panel-default">
      <div class="panel-heading">
        <small>
          {{ action.date_added|date:'M d, Y H:i' }}
        </small>
        <small>  <a href="{% url 'AARs:edit_action' action.id %}">Read or Edit Action</a></small>
      </div>
      <div class="panel-body">
        <small>
          {{ action.text|truncatewords_html:20 }}
        </small>
      </div>
    </div>
  {% empty %}
    No actions have been added yet.
  {% endfor %}

{% endblock content %}

AARs/templates/AARs/topics.html
{% extends "AARs/base.html" %}

{% block header %}
  <h1>Topics</h1>
{% endblock header %}

{% block content %}

  <ul>
    {% for topic in topics %}
      <li>
        <h3>
          <a href="{% url 'AARs:topic' topic.id %}">{{ topic }}</a>
        </h3>
      </li>

    {% empty %}
      <li>No topics have been added yet.</li>
    {% endfor %}
  </ul>

  <h3><a href="{% url 'AARs:new_topic' %}">Add a new topic:</a></h3>

{% endblock content %}

daily_AAR/templates/505.html
{% extends 'AARs/base.html' %}

{% block header %}
  <h2>There has been an internal error (500 error)</h2>
{% endblock header %}

users/templates/users/login.html
{% extends "AARs/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>Log in to your account.</h2>
{% endblock header %}

{% block content %}
  <form class="form" action="{% url 'users:login' %}" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
      <button name="submit" class="btn btn-primary">log in</button>
    {% endbuttons %}

    <input type="hidden" name="next" value="{% url 'AARs:index' %}"/>
  </form>
  
{% endblock content %}

users/templates/users/register.html
{% extends "AARs/base.html" %}

{% block content %}

  <form method="post" action="{% url 'users:register' %}">
    {% csrf_token %}
    {{ form.as_p }}

    <button name="submit">register</button>
    <input type="hidden" name="next" value="{% url 'AARs:index' %}"/>
  </form>

{% endblock content %}